services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APPDATA}/plex:/config
      - /tmp/plex:/transcode
      - ${DATA}/media:/data/media
    restart: unless-stopped
    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:32400]/web"
      net.unraid.docker.icon: "https://notifiarr.com/images/logo/plex.png?t=1725203811"
      net.unraid.docker.shell: "sh"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/tautulli:/config
    ports:
      - ${TAUTULLI_HOST_PORT}:8181
    restart: unless-stopped
    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:${TAUTULLI_HOST_PORT}]"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tautulli-icon.png"
      net.unraid.docker.shell: "sh"

  tunarr:
    image: ghcr.io/chrisbenincasa/tunarr:latest
    container_name: tunarr
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/tunarr:/config/tunarr
    ports:
      - ${TUNARR_HOST_PORT}:8000
    # Transcode to RAM
    tmpfs:
      - /transcode:size=10G
    # Pass all render devices to container (For Intel QSV)
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      net.unraid.docker.webui: "http://[IP]:[PORT:${TUNARR_HOST_PORT}]"
      net.unraid.docker.icon: "https://tunarr.com/assets/tunarr.png"
      net.unraid.docker.shell: "sh"
