services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${APPDATA}/plex:/config
      - /tmp/plex:/transcode
      - ${DATA}/media:/data/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/tautulli:/config
    ports:
      - ${TAUTULLI_HOST_PORT}:8181
    restart: unless-stopped

  tunarr:
    image: ghcr.io/chrisbenincasa/tunarr:latest
    container_name: tunarr
    depends_on:
      - plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/tunarr:/config/tunarr
    ports:
      - ${TUNARR_HOST_PORT}:8000
    restart: unless-stopped
