networks:
  pihole-net:
    driver: bridge

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
    environment:
      - TZ=${TZ}
      - FTLCONF_webserver_api_password=${PIHOLE_FTLCONF_webserver_api_password}
      - FTLCONF_dns_upstreams=${PIHOLE_FTLCONF_dns_upstreams}
      - FTLCONF_dns_listeningMode=all
    volumes:
      - ${APPDATA}/pihole:/etc/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_HTTP_PORT}:80/tcp
      - ${PIHOLE_HTTPS_PORT}:443/tcp
    restart: unless-stopped
    networks:
      - pihole-net