networks:
  media-net:
    driver: bridge

services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun-media
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${GLUETUN_WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT_PORT=${GLUETUN_WIREGUARD_ENDPOINT_PORT}
      - SERVER_CITIES=${GLUETUN_SERVER_CITIES}
      - FIREWALL_OUTBOUND_SUBNETS=${GLUETUN_FIREWALL_OUTBOUND_SUBNETS}
      # - VPN_PORT_FORWARDING=on
      # VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:${QBITTORRENT_WEBUI_PORT}/api/v2/app/setPreferences 2>&1'
      # - FIREWALL_VPN_INPUT_PORTS=${GLUETUN_VPN_INPUT_PORTS}
      - UPDATE_PERIOD=24h
      - SHADOWSOCKS=off
    volumes:
      - ${APPDATA}/gluetun:/config
    ports:
      - 8000:8000/tcp # Gluten HTTP Control
      # - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - "${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}"
      - "${QBITTORRENT_TORRENTING_PORT}:${QBITTORRENT_TORRENTING_PORT}"
      - "${QBITTORRENT_TORRENTING_PORT}:${QBITTORRENT_TORRENTING_PORT}/udp"
      - "${SONARR_HOST_PORT}:${SONARR_HOST_PORT}"
      - "${RADARR_HOST_PORT}:${RADARR_HOST_PORT}"
      - "${JACKETT_HOST_PORT}:${JACKETT_HOST_PORT}"
      - "${FLARESOLVERR_HOST_PORT}:${FLARESOLVERR_HOST_PORT}"
      - "${NOTIFIARR_HOST_PORT}:${NOTIFIARR_HOST_PORT}"
    networks:
      - media-net

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
      - TORRENTING_PORT=${QBITTORRENT_TORRENTING_PORT}
    volumes:
      - ${APPDATA}/qbittorrent:/config
      - ${DATA}/torrents:/data/torrents
    restart: unless-stopped
    network_mode: "service:gluetun"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/sonarr:/config
      - ${DATA}:/data
    restart: unless-stopped
    network_mode: "service:gluetun"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/radarr:/config
      - ${DATA}:/data
    restart: unless-stopped
    network_mode: "service:gluetun"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=${JACKETT_AUTO_UPDATE}
    volumes:
      - ${APPDATA}/jackett:/config
    restart: unless-stopped
    network_mode: "service:gluetun"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL}
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: "service:gluetun"

  notifiarr:
    container_name: notifiarr
    image: golift/notifiarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped
    network_mode: "service:gluetun"