networks:
  utils-net:
    driver: bridge

services:
  krusader:
    container_name: krusader
    image: binhex/arch-krusader:latest
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TEMP_FOLDER=${APPDATA}/krusader/tmp
      - VNC_PASSWORD=${KRUSADER_VNC_PASSWORD}
      - WEBPAGE_TITLE=${KRUSADER_WEBPAGE_TITLE}
      - WEBUI_PORT=${KRUSADER_WEBUI_PORT}
    volumes:
      - ${APPDATA}/krusader:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${KRUSADER_VNC_PORT}:5900
      - ${KRUSADER_WEBUI_PORT}:6080
    restart: unless-stopped
    networks:
      - utils-net