services:
  dashdot:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DASHDOT_SHOW_DASH_VERSION=${DASHDOT_SHOW_DASH_VERSION}
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=${DASHDOT_ALWAYS_SHOW_PERCENTAGES}
      - DASHDOT_PAGE_TITLE=${DASHDOT_PAGE_TITLE}
      - DASHDOT_ENABLE_CPU_TEMPS=${DASHDOT_ENABLE_CPU_TEMPS}
    volumes:
      - /:/mnt/host:ro
    ports:
      - ${DASHDOT_HOST_PORT}:3001
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
    volumes:
      - ${APPDATA}:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${HOMARR_HOST_PORT}:7575
    restart: unless-stopped