networks:
  notes-net:
    driver: bridge

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-notes
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - COUCHDB_USER=${COUCHDB_USER} 
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ${APP_DATA}/data:/opt/couchdb/data
      - ${APP_DATA}/etc:/opt/couchdb/etc/local.d
    ports:
      - "${COUCHDB_HOST_PORT}:5984"
    restart: unless-stopped
    networks:
      - notes-net
    healthcheck:
      test: curl --fail -s -u ${COUCHDB_USER}:${COUCHDB_PASSWORD} http://localhost:5984/_up | grep -Eo '\"status\":\"ok\"' || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "net.unraid.docker.webui=http://[IP]:[PORT:5984]/_utils" # for some reason this does not work properly
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/selfhst/icons/refs/heads/main/png/couchdb.png"
